_BASE_: Base-PointRend-Semantic-FPN.yaml
MODEL:
  RESNETS:
    DEPTH: 101
  SEM_SEG_HEAD:
    NUM_CLASSES: 3
    IGNORE_VALUE: 0
  POINT_HEAD:
    NUM_CLASSES: 3
    TRAIN_NUM_POINTS: 2048
    SUBDIVISION_NUM_POINTS: 8192
  DEVICE: "cuda"
DATASETS:
  TRAIN: ("floorplans_sem_seg_train",)
  TEST: ("floorplans_sem_seg_val",)
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 1
  STEPS: (40000, 55000)
  MAX_ITER: 160000
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1280, 1536, 1792, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 0.75
  COLOR_AUG_SSD: True
DATALOADER:
  NUM_WORKERS: 4
