_BASE_: Base-PointRend-Semantic-FPN.yaml
MODEL:
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 3
  POINT_HEAD:
    NUM_CLASSES: 3
    TRAIN_NUM_POINTS: 2048
    SUBDIVISION_NUM_POINTS: 8192
  DEVICE: "cuda"
DATASETS:
  TRAIN: ("floorplans_sem_seg_train",)
  TEST: ("floorplans_sem_seg_val",)
SOLVER:
  BASE_LR: 0.0001
  IMS_PER_BATCH: 1
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
  RANDOM_FLIP: "none"
  COLOR_AUG_SSD: False
DATALOADER:
  NUM_WORKERS: 10
